config/routes.rb
Rails.application.routes.draw do
  resources :condos
  devise_for :users
  root 'static_pages#home'

end

app/models/condo.rb
class Condo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/condos_controller.rb
class CondosController < ApplicationController
  before_action :set_condo, only: [:show, :edit, :update, :destroy]

  # GET /condos
  # GET /condos.json
  def index
    @condos = Condo.all
  end

  # GET /condos/1
  # GET /condos/1.json
  def show
  end

  # GET /condos/new
  def new
  if current_user 
    @condo = Condo.new
  else
    redirect_to root_path
  end
  end

  # GET /condos/1/edit
  def edit
  end

  # POST /condos
  # POST /condos.json
  def create
    @condo = Condo.new(condo_params)
    @condo.user = current_user 

    respond_to do |format|
      if @condo.save
        format.html { redirect_to @condo, notice: 'Condo was successfully created.' }
        format.json { render :show, status: :created, location: @condo }
      else
        format.html { render :new }
        format.json { render json: @condo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /condos/1
  # PATCH/PUT /condos/1.json
  def update
    respond_to do |format|
      if @condo.update(condo_params)
        format.html { redirect_to @condo, notice: 'Condo was successfully updated.' }
        format.json { render :show, status: :ok, location: @condo }
      else
        format.html { render :edit }
        format.json { render json: @condo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /condos/1
  # DELETE /condos/1.json
  def destroy
    @condo.destroy
    respond_to do |format|
      format.html { redirect_to condos_url, notice: 'Condo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condo
      @condo = Condo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condo_params
      params.require(:condo).permit(:name, :street_address, :post_code, :phone_number)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/condos_helper.rb
module CondosHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/condos/_form.html.erb
<%= form_for(@condo, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @condo.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@condo.errors.count, "error") %> prohibited this condo from being saved:</h4>

      <ul>
      <% @condo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :street_address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :street_address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :post_code, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :post_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/condos/edit.html.erb
<div class="page-header">
  <%= link_to condos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @condo, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing condo</h1>
</div>

<%= render 'form' %>

app/views/condos/index.html.erb
<div class="page-header">
  <%= link_to new_condo_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Condo
  <% end %>
  <h1>Listing condos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Street address</th>
            <th>Post code</th>
            <th>Phone number</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @condos) do |condo| %>
            <td><%= condo.name %></td>
            <td><%= condo.street_address %></td>
            <td><%= condo.post_code %></td>
            <td><%= condo.phone_number %></td>
            <td><%= link_to 'Show', condo, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_condo_path(condo), class: "btn btn-info" %></td>
        <td><%= link_to 'Destroy', condo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/condos/new.html.erb
<div class="page-header">
  <%= link_to condos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New condo</h1>
</div>

<%= render 'form' %>

app/views/condos/show.html.erb
<div class="page-header">
  <%= link_to condos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_condo_path(@condo), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show condo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @condo.name %></dd>

  <dt>Street address:</dt>
  <dd><%= @condo.street_address %></dd>

  <dt>Post code:</dt>
  <dd><%= @condo.post_code %></dd>

  <dt>Phone number:</dt>
  <dd><%= @condo.phone_number %></dd>

</dl>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Cleaning Service", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Register",new_user_registration_path%> </li>
        <% if user_signed_in? %> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "edit profile", edit_user_registration_path %></li>
              <li><%= link_to "view your listing", condos_path%> </li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "sign out",  destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <%else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <%end %>
      </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %> 
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Homepage</h1>
  <p>This is the Content of the first page make it interesting!</p>
  <p>I think it works now!! </p>
  <%= link_to "Sign Up to our App", '#', class: "btn btn-lg btn-primary" %> 
</div>